### ISSUE TITLE
Embassy release TODO

### ISSUE THREAD

**Issue by lulf** [embassy-rs/embassy#1050]
This is an attempt at capturing remaining work needed for crate releases. Feel free to edit/propose changes.

## General

* [x] Remove `make_static!` in examples
* [x] Change CI to use 1.75 beta

## HAL

* [x] embassy-hal-common
  * [x] document public APIs
* [x] embassy-embedded-hal
  * [x] document public APIs
* [x] embassy-nrf
  * [x] dependencies: embassy-hal-common, embassy-embedded-hal, embassy-usb-driver
  * [x] document public APIs
* [x] embassy-stm32
  * [x] dependencies: embassy-hal-common, embassy-embedded-hal, embassy-usb-driver, embassy-net
  * [x] document public APIs
  * [x] git dep: `stm32-metapac`
  * [x] git dep: `embedded-sdmmc` async fork (probably remove it?)
* [x] embassy-rp
  * [x] document public APIs
* [x] cyw43
  * [x] document public APIs
* [x] cyw43-pio
  * [x] document public APIs

## Boot

* [x] embassy-boot: ready!
  * [x] git dep: `salty`
* [x] embassy-boot-nrf
  * dependencies: embassy-nrf, embassy-boot
  * [x] git dep: `nrf-softdevice-mbr`
* [x] embassy-boot-stm32
  * [x] dependencies: embassy-stm32, embassy-boot
* [x] embassy-boot-rp
  * [x] dependencies: embassy-rp, embassy-boot

## USB

* [x] embassy-usb
  * [x] document public APIs
  * [x] dependencies: embassy-usb-driver
* [x] embassy-usb-driver
  * [x] document public APIs
* [x] embassy-usb-logger
  * [x] document public APIs

## Net

* [x] embassy-net
  * [x] document public APIs
  * [x] use a non-git smoltcp version
  * [x] git dep: `smoltcp`
* [x] embassy-net-driver
* [x] embassy-net-driver-channel
  * [x] Document public APIs
* [x] embassy-net-adin1110
  * [x] Document public APIs
* [x] embassy-net-enc28j60
  * [x] Document public APIs
* [x] embassy-net-esp-hosted
  * [x] Document public APIs
  * [x] git dep: noproto
* [x] embassy-net-ppp
  * [x] Document public APIs
* [x] embassy-net-tuntap
  * [x] Document public APIs
* [x] embassy-net-wiznet
  * [x] Document public APIs

**Comment by elpiel** [comment]
It would be nice to add `embassy-rp` to the release tasks too.

**Comment by JuliDi** [comment]
What's the preferred way of documentation w.r.t. this planned release?
Single function documentation as docstrings, sure.
But for bigger "how to" guides or MWEs, should they go on the website, docstrings at the module level or as per-chip examples (like we currently have but with more documentation) or a"book"?

I'd be open to documenting more stuff as I progress in my projects using embassy. Having a stable release soon-ish would be great.

**Comment by elpiel** [comment]
@lulf many of the crates were recently released on crates.io.
Could we update this issue to reflect this and see if there are any remaining tasks (crates to be released)?

**Comment by lulf** [comment]
All is released from what I can tell, closing.
