### ISSUE TITLE
STM32 DMA tracking issue

### ISSUE THREAD

**Issue by Dirbaio** [embassy-rs/embassy#291]
## DMA versions

- [x] BDMAv1:  F0 except below, F1,  F3, L1
    no request selection capabilities. Each DMA channel is the OR of a 
    hardcoded set of peripherals. Two peripherals that are associated
    to the same DMA channel can't be used with DMA at the same time, AT ALL.

- [x] BDMAv2:  L0, L4, F030xC, F09xxx
    BDMAv2 has CSELR, allowing each channel to choose from a hardcoded set of DMA reqs.
    Some flexibility, no total flexibility yet.

- [x] DMAv2:  F2, F4, F7
    DMAv2 has CHSEL, allowing each channel to choose from a hardcoded set of DMA reqs.
    Some flexibility, no total flexibility yet.

- [x] BDMAv1 + DMAMUX:  L4+, L5, G0, G4, WB, WL
    Each BDMA channel receives requests from a hardcoded DMAMUX channel.
    DMAMUX can route ANY request to ANY channel. Total flexibility.
    It's BDMAv1 instead of BDMAv2 because it wouldn't make sense to have CSELR,
    because the DMAMUX can already mux.

- [x] BDMAv1 + DMAv1 + DMAMUX:  H7
    it has EVERYTHING, because why not??
    Each DMA or BDMA channel receives requests from a hardcoded DMAMUX channel.
    DMAMUX can route ANY request to ANY channel. Total flexibility.
    It's BDMAv1 instead of BDMAv2 because it wouldn't make sense to have CSELR,
    because the DMAMUX can already mux.

## DMA peripehral integration

- [x] USART v1
- [x] USART v2
- [x] SPI v1
- [x] SPI v2
- [x] SPI v3
- [ ] I2C v1
- [ ] I2C v2

## Driver infrastructure

- [ ] Blocking DMA
    Currently blocking impls are only enabled when creating drivers with `NoDma`. We should allow using them with DMA too. Blocking operations would start DMA then spin-wait for it to finish. There's still *some* benefits. 1. data keeps being copied even while the current thread is preempted. 2. allows mixing blocking and async calls, can improve code size in some cases.

- [ ] Async Non-DMA
    Currently async impls are only enabled when creating drivers with DMA. It might be useful to allow async impls without DMA. These would store buffer pointers in the "State", read/write to the buffer from interrupts, and wake the task when done. [nRF's RNG](https://github.com/embassy-rs/embassy/blob/master/embassy-nrf/src/rng.rs#L34) does this. It's unclear whether the benefit is worth the very high complexity though.

**Comment by Dirbaio** [comment]
DMA is now fully implemented in embassy-stm32.

MIssing bit is blocking DMA, tracked separately: #621
We're not going to do async non-DMA, performance is terrible with the interrupt spam.
